apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  namespace: flashflow-ns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      terminationGracePeriodSeconds: 15
      securityContext:
        runAsNonRoot: true
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: stock-service
          image: gaurav598/stock-service:v1
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - { name: REDIS_HOST, value: "redis" }
            - { name: REDIS_PORT, value: "6379" }
          envFrom:
            - secretRef:
                name: flashflow-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          readinessProbe:
            httpGet: { path: /health/ready, port: 3002 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health/live, port: 3002 }
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: flashflow-ns
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
